### ISSUE TITLE
Error on Yarn dev

### ISSUE THREAD

**Issue by BenP1236691** [linux-odyssey/linux-odyssey#145]
root@vultr:~/linux-odyssey# yarn dev
yarn run v1.22.22
$ concurrently -n "App,Server" -c "bgBlue.bold,bgGreen.bold" "yarn workspace app dev" "yarn workspace server dev"
/root/linux-odyssey/node_modules/concurrently/dist/src/command.js:78
                exitCode: exitCode ?? String(signal),
                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/root/linux-odyssey/node_modules/concurrently/dist/src/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lancatlin** [comment]
Should have been fixed in #179
